# Generated by Django 4.2.23 on 2025-07-24 07:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_title', models.CharField(blank=True, max_length=200, null=True)),
                ('assignment_date', models.DateField(blank=True, null=True)),
                ('assignment_due_date', models.DateField(blank=True, null=True)),
                ('assignment_submission_date', models.DateField(blank=True, null=True)),
                ('assignment_marks', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_classes', models.IntegerField(default=0)),
                ('classes_attended', models.IntegerField(default=0)),
                ('overall_progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progress_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('on_track', 'On Track'), ('behind', 'Behind'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('instructor_notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='MS.studentcourse')),
            ],
            options={
                'verbose_name': 'Student Progress',
                'verbose_name_plural': 'Student Progress',
            },
        ),
    ]
